# Generated by Django 5.0.3 on 2024-04-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_category_articles_article_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_categories', to='articles.article', verbose_name='Статья')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_categories', to='articles.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория статьи',
                'verbose_name_plural': 'Категории статей',
                'unique_together': {('category', 'article')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='related_articles', through='articles.ArticleCategory', to='articles.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='articles',
            field=models.ManyToManyField(related_name='related_categories', through='articles.ArticleCategory', to='articles.article', verbose_name='Статьи'),
        ),
    ]
